# Model config
model:
  name: xgboost        
  params: {}           

# Hyperparameter Search Space (لـ Optuna)
search_space:
  xgboost:
    n_estimators: [50, 300]
    max_depth: [2, 10]
    learning_rate: [0.01, 0.3]
    subsample: [0.5, 1.0]

  random_forest:
    n_estimators: [50, 300]
    max_depth: [2, 10]
    criterion: ["gini", "entropy"]

  lightgbm:
    n_estimators: [50, 300]
    max_depth: [2, 10]
    learning_rate: [0.01, 0.3]

# Data config
data:
  path: data/processed/train.parquet
  target: Survived

# Training config
training:
  test_size: 0.1
  n_trials: 20
  random_state: 42

split:
  data_path: data/raw/Titanic-Dataset.csv
  target_col: Survived
  test_size: 0.2
  random_state: 42

evaluation:
  model_path: models/model_pipeline.pkl
  test_data_path: data/processed/test.parquet
  target_col: Survived
  report_path: reports/evaluation_report.json
  registry_stage: champion1
  registry_model_name: Titanic_Classifier_Model
